apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
  labels:
    tier: frontend
    app: nginx
spec:
  selector:
    matchLabels:
      app: nginx
  replicas: 3
  template:
    metadata:
      name: nginx-2
      labels:
        app: nginx
    spec:
      containers:
        - name: nginx
          image: nginx:1.24
  
