apiVersion: apps/v1
kind: Deployment # Deployment automatically creates a replica set from given template
metadata:
  name: postgres-deployment
  labels:
    app: postgres

spec:
  selector:
    matchLabels:
      app: postgres
  replicas: 1
 
  template:
    metadata:
      name: postgres-pod
      labels:
        app: postgres
    spec:
      containers:
      - name: postgres
        image: postgres
        ports:
          - containerPort: 5432
        env:
          - name: POSTGRES_PASSWORD
            value: postgres