apiVersion: v1
kind: Service
metadata:
  name: nginx-clusterip-service

spec:
  type: ClusterIP # this service is not ment to be exposed externally, but can be used to communicate within the cluster
  ports:
    - port: 80 # service port
      targetPort: 80 # port exposed on the pod  
  selector:
    app: nginx
