apiVersion: v1
kind: PersistentVolume
metadata:
  name: persistent-volume-hostpath
  labels:
    type: persistent-volume-local
spec:
  #kubectl get storageclass
  storageClassName: hostpath
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/data/pv"