apiVersion: v1
kind: Pod
metadata:
  name: postgres-pod
  labels:
    app: postgres
spec:
  containers:
    - name: postgres
      image: postgres
      ports:
        - containerPort: 5432
      env:
        - name: POSTGRES_PASSWORD
          value: postgres

# v check if postgres works in pod
# v expose it through a service and check if it works
# v deploy postgres in Deployment (or StatefulSet)
# check what storage classes does minikube have
# add persistant volume object to your kubernetes
# add persistant volume claim to the deployment (or StatefulSet) with postgres 